apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: schoolofdevops/vote:v1
    ports:
      - containerPort: 7070
        protocol: TCP
