version: "3"
networks: 
  vote: 
    driver: bridge

services: 
    vote: 
      image: vote
      ports: 
        - 9090
      networks: 
        - vote
      depends_on: 
        - redis

    redis: 
      image: redis:alpine
      networks: 
        - vote
    